"""
Discovery models - domain discovery and preference schema generation.
"""
from typing import Any, Literal, Optional

from pydantic import BaseModel, Field


class AttributeCandidate(BaseModel):
    """
    A discovered attribute that's relevant for this product domain.
    Generated by analyzing listing texts.
    """
    name: str = Field(description="Attribute name, e.g. 'storage_gb', 'battery_health'")
    display_name: str = Field(description="Human-readable name for UI")
    type: Literal["text", "number", "enum", "boolean"] = Field(description="Data type")
    allowed_values: Optional[list[str]] = Field(default=None, description="For enum type")
    value_range: Optional[tuple[float, float]] = Field(default=None, description="For number type")
    importance_weight: float = Field(default=0.5, ge=0, le=1, description="How important for scoring")
    critical_if_missing: bool = Field(default=False, description="Should flag if missing")
    evidence_terms: list[str] = Field(default_factory=list, description="Terms found in listings")
    prevalence_estimate: float = Field(default=0.5, ge=0, le=1, description="How often found in listings")


class PreferenceQuestion(BaseModel):
    """
    A question to ask the user about their preferences.
    Dynamically generated based on domain discovery.
    """
    question_id: str = Field(description="Unique ID for the question")
    question_text: str = Field(description="The question to display")
    maps_to_attribute: str = Field(description="Which attribute this answers")
    answer_type: Literal["single_choice", "multi_choice", "range", "boolean", "text"]
    options: list[str] = Field(default_factory=list, description="For choice types")
    default_value: Optional[Any] = Field(default=None)
    is_required: bool = Field(default=False)
    tooltip: Optional[str] = Field(default=None, description="Why this question matters")


class InferredDomain(BaseModel):
    """Inferred product domain/category."""
    domain_label: str = Field(description="e.g. 'smartphone', 'bicycle', 'furniture'")
    confidence: float = Field(ge=0, le=1)
    subcategory: Optional[str] = Field(default=None, description="More specific category")
    
    # Clarification when uncertain
    clarifying_question: Optional[str] = Field(
        default=None,
        description="Question to ask user if confidence < 0.7"
    )
    clarifying_options: list[str] = Field(
        default_factory=list,
        description="Suggested options for clarification"
    )
    
    @property
    def needs_clarification(self) -> bool:
        """Check if we need to ask the user for clarification."""
        return self.confidence < 0.7 and self.clarifying_question is not None


class DomainDiscoveryOutput(BaseModel):
    """
    Complete output from domain discovery.
    This defines the schema for evaluating listings in this domain.
    """
    schema_version: str = Field(default="1.0.0")
    
    # Domain identification
    inferred_domain: InferredDomain
    
    # Discovered attributes
    attribute_candidates: list[AttributeCandidate] = Field(default_factory=list)
    
    # Generated preference questions
    preference_questions: list[PreferenceQuestion] = Field(default_factory=list)
    
    # Normalization rules for text processing
    normalization_rules: dict[str, list[str]] = Field(
        default_factory=dict,
        description="Mapping of canonical values to variations"
    )
    
    # Common patterns in missing info
    missing_info_patterns: list[str] = Field(
        default_factory=list,
        description="What's commonly missing from listings"
    )
    
    # Domain-specific risk indicators
    domain_risk_notes: list[str] = Field(
        default_factory=list,
        description="What to watch out for in this domain"
    )
    
    # Sample analysis metadata
    sample_size: int = Field(default=0, description="How many listings were analyzed")
    discovery_timestamp: Optional[str] = Field(default=None)


# Default fallback schema when discovery fails
DEFAULT_GENERIC_SCHEMA = DomainDiscoveryOutput(
    inferred_domain=InferredDomain(
        domain_label="generic",
        confidence=0.0,
    ),
    attribute_candidates=[
        AttributeCandidate(
            name="condition",
            display_name="Skick",
            type="enum",
            allowed_values=["Ny", "Som ny", "Bra", "OK", "Defekt"],
            importance_weight=0.8,
            critical_if_missing=True,
        ),
        AttributeCandidate(
            name="has_receipt",
            display_name="Kvitto",
            type="boolean",
            importance_weight=0.3,
        ),
        AttributeCandidate(
            name="delivery_available",
            display_name="Leverans",
            type="boolean",
            importance_weight=0.2,
        ),
        AttributeCandidate(
            name="defects",
            display_name="Defekter/skador",
            type="text",
            importance_weight=0.7,
            critical_if_missing=False,
        ),
    ],
    preference_questions=[
        PreferenceQuestion(
            question_id="q_condition",
            question_text="Vilket skick är acceptabelt?",
            maps_to_attribute="condition",
            answer_type="multi_choice",
            options=["Ny", "Som ny", "Bra", "OK", "Defekt"],
            default_value=["Ny", "Som ny", "Bra"],
        ),
        PreferenceQuestion(
            question_id="q_max_price",
            question_text="Maxpris?",
            maps_to_attribute="max_price",
            answer_type="range",
            is_required=False,
        ),
        PreferenceQuestion(
            question_id="q_delivery",
            question_text="Måste kunna skickas?",
            maps_to_attribute="delivery_available",
            answer_type="boolean",
            default_value=False,
        ),
    ],
    missing_info_patterns=["skick inte angivet", "pris saknas", "inga bilder"],
    domain_risk_notes=["Ovanligt lågt pris", "Ny användare utan omdömen", "Brådskandeord"],
)
